backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/launches.md"
        label: "Launches Page"
        name: "launches"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: launches}
          - {label: Page, name: page, widget: hidden, default: "/launches.html"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Directions, name: directions, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Places, name: places, widget: list, fields: [{label: Map, name: map, widget: string}, {label: Text, name: text, widget: text}]}]}
          - {label: Notices, name: notices, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "site/content/membership.md"
        label: "Membership Page"
        name: "membership"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: memebrship}
          - {label: Page, name: page, widget: hidden, default: "/membership.html"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Annual Fees, name: annual fees, widget: object, fields: [{label: Blurb, name: blurb, widget: text}, {label: Fee, name: fee, widget: list, fields: [{label: Type, name: type, widget: string}, {label: cost, name: cost, widget: string]}]}
        
  - name: "membership" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Membership" # Used in the UI, ie.: "New Post"
    folder: "site/content/membership" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}]}]}
  